### ISSUE TITLE
PHP Fatal error:  Class 'InfluxDB\ClientFactory' not found

### ISSUE THREAD

**Issue by skynet** [corley/influxdb-php-sdk#68]
`PHP Fatal error:  Class 'InfluxDB\ClientFactory' not found`

Did the API change?

**Comment by wdalmut** [comment]
We have dropped out the support for the `ClientFactory` for version >=0.8.* but it still exists for v0.7.* we have a major BC Break from v0.7 to v0.8 and we have deprecated few methods for v0.8 to v0.9

We redesign some parts of the library in version 0.8 and we believe that users can use their `ServiceLocator`, `DIC` or any other solution in order to compose the library.

## Symfony Dependecy Injection v0.9

```yaml
services:
  influxdb:
    class: InfluxDB\Client
    arguments: ["@influxdb_reader", "@influxdb_writer"]

  influxdb_http_client:
    class: GuzzleHttp\Client

  influxdb_reader:
    class: InfluxDB\Adapter\Http\Reader
    arguments: ["@influxdb_http_client", "@influxdb_http_options"]

  influxdb_writer:
    class: InfluxDB\Adapter\Udp\Writer
    arguments: ["@influxdb_udp_options"]

  influxdb_udp_options:
    class: InfluxDB\Adapter\Udp\Options
    calls:
      - ["setHost", ["%influxdb_host%"]]
      - ["setPort", ["%influxdb_udp_port%"]]
      - ["setTags", [{"env": "%kernel.environment%"}]]
  influxdb_http_options:
    class: InfluxDB\Adapter\Http\Options
    calls:
      - ["setDatabase", ["%influxdb_db_name%"]]
      - ["setHost", ["%influxdb_host%"]]
      - ["setPort", ["%influxdb_http_port%"]]
```

## Zend ServiceManager v0.9

```php
"services" => [
  "factory" => function() {
    $reader = new Http\Options();

    $options = new Udp\Options();
    $options->...
    $writer = new Udp\Writer($options);

    $client = new Client($reader, $writer);
    return $client;
  }
],
```
